(
// this can't be changed while the sequencer is running, needs fix
~score1 = `[ [\saw, [\frq, 66]],
	[\saw, [\frq, 80]],
	[\saw, [\frq, 2500, \len, 0.01, \amp, 0.25]],
	[\saw, [\frq, 70, \len, 0.09]],
	[\saw, [\frq, 1000, \len, 0.02]],
	[\saw, [\frq, 950, \len, 0.01, \amp, 0.25]],
	[\saw, [\frq, 50, \len, 0.09, \amp, 0.3]],
	[\saw, [\frq, 45, \len, 0.05, \amp, 0.7]],
	[\saw, [\frq, 50, \len, 0.09, \amp, 0.5]],
	[\saw, [\frq, 5000, \len, 0.02]]
]
)
